### ISSUE TITLE
Not working from the command line

### ISSUE THREAD

**Issue by cayhorstmann** [runarberg/ascii2mathml#22] opened 2018-10-17 16:21 UTC
I installed Node 10.12.0 and can't run from the command line. 
```
$ ascii2mathml 
/home/cay/node_modules/ascii2mathml/index.js:1
(function (exports, require, module, __filename, __dirname) { import parser from "./lib/parser";
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

Any idea what I can do to get past this? I used a prior version at one time and had no trouble.

**Comment by lukasbestle** [comment] 2018-10-17 18:36
See #21.

**Comment by runarberg** [comment] 2019-03-10 02:36
Closing duplicate of #21

**Closed by runarberg** 2019-03-10 02:36 UTC
